package com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member

import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.congregation.MemberCongregationCrossRefCsvListToMemberCongregationCrossRefEntityListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.congregation.MemberCongregationCrossRefEntityListToMemberCongregationCrossRefCsvListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.movement.MemberMovementCsvListToMemberMovementEntityListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.movement.MemberMovementEntityListToMemberMovementCsvListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.role.MemberRoleCsvListToMemberRoleEntityListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.role.MemberRoleEntityListToMemberRoleCsvListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.transfer.RoleTransferObjectCsvListToRoleTransferObjectEntityListMapper
import com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.transfer.RoleTransferObjectEntityListToRoleTransferObjectCsvListMapper

data class MemberCsvMappers(
    val memberEntityListToMemberCsvListMapper: MemberEntityListToMemberCsvListMapper,
    val memberCongregationCrossRefEntityListToMemberCongregationCrossRefCsvListMapper: MemberCongregationCrossRefEntityListToMemberCongregationCrossRefCsvListMapper,
    val memberMovementEntityListToMemberMovementCsvListMapper: MemberMovementEntityListToMemberMovementCsvListMapper,
    val memberRoleEntityListToMemberRoleCsvListMapper: MemberRoleEntityListToMemberRoleCsvListMapper,
    val roleTransferObjectEntityListToRoleTransferObjectCsvListMapper: RoleTransferObjectEntityListToRoleTransferObjectCsvListMapper,

    val memberCsvListToMemberEntityListMapper: MemberCsvListToMemberEntityListMapper,
    val memberCongregationCrossRefCsvListToMemberCongregationCrossRefEntityListMapper: MemberCongregationCrossRefCsvListToMemberCongregationCrossRefEntityListMapper,
    val memberMovementCsvListToMemberMovementEntityListMapper: MemberMovementCsvListToMemberMovementEntityListMapper,
    val memberRoleCsvListToMemberRoleEntityListMapper: MemberRoleCsvListToMemberRoleEntityListMapper,
    val roleTransferObjectCsvListToRoleTransferObjectEntityListMapper: RoleTransferObjectCsvListToRoleTransferObjectEntityListMapper
)
