package com.oborodulin.jwsuite.presentation_territory.ui.model.mappers.report

import com.oborodulin.home.common.mapping.ListMapperImpl
import com.oborodulin.jwsuite.domain.model.territory.TerritoryMemberReport
import com.oborodulin.jwsuite.presentation_territory.ui.model.TerritoryMemberReportsListItem

class TerritoryMemberReportsListToTerritoryMemberReportsListItemMapper(mapper: TerritoryMemberReportToTerritoryMemberReportsListItemMapper) :
    ListMapperImpl<TerritoryMemberReport, TerritoryMemberReportsListItem>(mapper)