package com.oborodulin.jwsuite.presentation_territory.ui.model.mappers.report

import com.oborodulin.home.common.mapping.ListMapperImpl
import com.oborodulin.jwsuite.domain.model.territory.TerritoryHouseReport
import com.oborodulin.jwsuite.presentation_territory.ui.model.TerritoryHouseReportsListItem

class TerritoryHouseReportsListToTerritoryHouseReportsListItemMapper(mapper: TerritoryHouseReportToTerritoryHouseReportsListItemMapper) :
    ListMapperImpl<TerritoryHouseReport, TerritoryHouseReportsListItem>(mapper)