package com.oborodulin.jwsuite.data_congregation.local.csv.mappers.member.congregation

import com.oborodulin.home.common.mapping.ListMapperImpl
import com.oborodulin.jwsuite.data_congregation.local.db.entities.MemberCongregationCrossRefEntity
import com.oborodulin.jwsuite.domain.services.csv.model.congregation.MemberCongregationCrossRefCsv

class MemberCongregationCrossRefEntityListToMemberCongregationCrossRefCsvListMapper(mapper: MemberCongregationCrossRefEntityToMemberCongregationCrossRefCsvMapper) :
    ListMapperImpl<MemberCongregationCrossRefEntity, MemberCongregationCrossRefCsv>(mapper)