package com.oborodulin.jwsuite.data_territory.local.db.mappers.territory.report

data class TerritoryReportMappers(
    val territoryMemberReportViewListToTerritoryMemberReportsListMapper: TerritoryMemberReportViewListToTerritoryMemberReportsListMapper,
    val territoryReportHouseViewListToTerritoryReportHousesListMapper: TerritoryReportHouseViewListToTerritoryReportHousesListMapper,
    val territoryReportRoomViewListToTerritoryReportRoomsListMapper: TerritoryReportRoomViewListToTerritoryReportRoomsListMapper,
    val territoryMemberReportEntityToTerritoryMemberReportMapper: TerritoryMemberReportEntityToTerritoryMemberReportMapper,
    val territoryMemberReportEntityListToTerritoryMemberReportsListMapper: TerritoryMemberReportEntityListToTerritoryMemberReportsListMapper,
    val territoryMemberReportToTerritoryMemberReportEntityMapper: TerritoryMemberReportToTerritoryMemberReportEntityMapper,
    val territoryReportHouseToTerritoryMemberReportEntityMapper: TerritoryReportHouseToTerritoryMemberReportEntityMapper,
    val territoryReportRoomToTerritoryMemberReportEntityMapper: TerritoryReportRoomToTerritoryMemberReportEntityMapper
)
