package com.oborodulin.jwsuite.data_geo.remote.osm.mappers.georegiondistrict

data class GeoRegionDistrictApiMappers(
    val regionDistrictElementsListToGeoRegionDistrictsListMapper: RegionDistrictElementsListToGeoRegionDistrictsListMapper
)
