package com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport

import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.house.TerritoryReportHouseToTerritoryMemberReportEntityMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.house.TerritoryReportHouseViewListToTerritoryReportHousesListMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.house.TerritoryReportHouseViewToTerritoryReportHouseMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.room.TerritoryReportRoomToTerritoryMemberReportEntityMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.room.TerritoryReportRoomViewListToTerritoryReportRoomsListMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.room.TerritoryReportRoomViewToTerritoryReportRoomMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.street.TerritoryReportStreetViewListToTerritoryReportStreetsListMapper
import com.oborodulin.jwsuite.data_territory.local.db.mappers.territoryreport.street.TerritoryReportStreetViewToTerritoryReportStreetMapper

data class TerritoryReportMappers(
    val territoryMemberReportViewListToTerritoryMemberReportsListMapper: TerritoryMemberReportViewListToTerritoryMemberReportsListMapper,
    val territoryReportStreetViewToTerritoryReportStreetMapper: TerritoryReportStreetViewToTerritoryReportStreetMapper,
    val territoryReportStreetViewListToTerritoryReportStreetsListMapper: TerritoryReportStreetViewListToTerritoryReportStreetsListMapper,
    val territoryReportHouseViewToTerritoryReportHouseMapper: TerritoryReportHouseViewToTerritoryReportHouseMapper,
    val territoryReportHouseViewListToTerritoryReportHousesListMapper: TerritoryReportHouseViewListToTerritoryReportHousesListMapper,
    val territoryReportRoomViewToTerritoryReportRoomMapper: TerritoryReportRoomViewToTerritoryReportRoomMapper,
    val territoryReportRoomViewListToTerritoryReportRoomsListMapper: TerritoryReportRoomViewListToTerritoryReportRoomsListMapper,
    val territoryMemberReportEntityToTerritoryMemberReportMapper: TerritoryMemberReportEntityToTerritoryMemberReportMapper,
    val territoryMemberReportEntityListToTerritoryMemberReportsListMapper: TerritoryMemberReportEntityListToTerritoryMemberReportsListMapper,
    val territoryMemberReportToTerritoryMemberReportEntityMapper: TerritoryMemberReportToTerritoryMemberReportEntityMapper,
    val territoryReportHouseToTerritoryMemberReportEntityMapper: TerritoryReportHouseToTerritoryMemberReportEntityMapper,
    val territoryReportRoomToTerritoryMemberReportEntityMapper: TerritoryReportRoomToTerritoryMemberReportEntityMapper
)
