package com.oborodulin.jwsuite.data_territory.local.csv.mappers.territory

import com.oborodulin.jwsuite.data_territory.local.csv.mappers.territory.congregation.CongregationTerritoryCrossRefCsvListToCongregationTerritoryCrossRefEntityListMapper
import com.oborodulin.jwsuite.data_territory.local.csv.mappers.territory.congregation.CongregationTerritoryCrossRefEntityListToCongregationTerritoryCrossRefCsvListMapper
import com.oborodulin.jwsuite.data_territory.local.csv.mappers.territory.member.TerritoryMemberCrossRefCsvListToTerritoryMemberCrossRefEntityListMapper
import com.oborodulin.jwsuite.data_territory.local.csv.mappers.territory.member.TerritoryMemberCrossRefEntityListToTerritoryMemberCrossRefCsvListMapper

data class TerritoryCsvMappers(
    val territoryEntityListToTerritoryCsvListMapper: TerritoryEntityListToTerritoryCsvListMapper,
    val congregationTerritoryCrossRefEntityListToCongregationTerritoryCrossRefCsvListMapper: CongregationTerritoryCrossRefEntityListToCongregationTerritoryCrossRefCsvListMapper,
    val territoryMemberCrossRefEntityListToTerritoryMemberCrossRefCsvListMapper: TerritoryMemberCrossRefEntityListToTerritoryMemberCrossRefCsvListMapper,

    val territoryCsvListToTerritoryEntityListMapper: TerritoryCsvListToTerritoryEntityListMapper,
    val congregationTerritoryCrossRefCsvListToCongregationTerritoryCrossRefEntityListMapper: CongregationTerritoryCrossRefCsvListToCongregationTerritoryCrossRefEntityListMapper,
    val territoryMemberCrossRefCsvListToTerritoryMemberCrossRefEntityListMapper: TerritoryMemberCrossRefCsvListToTerritoryMemberCrossRefEntityListMapper
)
