package com.oborodulin.jwsuite.data_geo.local.csv.mappers.geolocalitydistrict

import com.oborodulin.jwsuite.data_geo.local.csv.mappers.geolocalitydistrict.tl.GeoLocalityDistrictTlCsvListToGeoLocalityTlEntityListMapper
import com.oborodulin.jwsuite.data_geo.local.csv.mappers.geolocalitydistrict.tl.GeoLocalityDistrictTlEntityListToGeoLocalityDistrictTlCsvListMapper

data class GeoLocalityDistrictCsvMappers(
    val geoLocalityDistrictEntityListToGeoLocalityDistrictCsvListMapper: GeoLocalityDistrictEntityListToGeoLocalityDistrictCsvListMapper,
    val geoLocalityDistrictCsvListToGeoLocalityDistrictEntityListMapper: GeoLocalityDistrictCsvListToGeoLocalityDistrictEntityListMapper,
    val geoLocalityDistrictTlEntityListToGeoLocalityDistrictTlCsvListMapper: GeoLocalityDistrictTlEntityListToGeoLocalityDistrictTlCsvListMapper,
    val geoLocalityDistrictTlCsvListToGeoLocalityTlEntityListMapper: GeoLocalityDistrictTlCsvListToGeoLocalityTlEntityListMapper
)
