package com.oborodulin.jwsuite.data_congregation.local.csv.mappers.transfer

data class TransferObjectCsvMappers(
    val transferObjectEntityListToTransferObjectCsvListMapper: TransferObjectEntityListToTransferObjectCsvListMapper,
    val transferObjectCsvListToTransferObjectEntityListMapper: TransferObjectCsvListToTransferObjectEntityListMapper
)
