package com.oborodulin.jwsuite.data_congregation.local.db.mappers.transfer

import com.oborodulin.jwsuite.data_congregation.local.db.mappers.member.role.transfer.MemberRoleTransferObjectToRoleTransferObjectEntityMapper
import com.oborodulin.jwsuite.data_congregation.local.db.mappers.member.role.transfer.MemberRoleTransferObjectViewListToMemberRoleTransferObjectsListMapper
import com.oborodulin.jwsuite.data_congregation.local.db.mappers.member.role.transfer.MemberRoleTransferObjectViewListToTransferObjectsListMapper
import com.oborodulin.jwsuite.data_congregation.local.db.mappers.member.role.transfer.MemberRoleTransferObjectViewToMemberRoleTransferObjectMapper
import com.oborodulin.jwsuite.data_congregation.local.db.mappers.member.role.transfer.MemberRoleTransferObjectViewToTransferObjectMapper
import com.oborodulin.jwsuite.data_congregation.local.db.mappers.role.transfer.RoleTransferObjectViewListToRoleTransferObjectsListMapper

data class TransferObjectMappers(
    val transferObjectEntityToTransferObjectMapper: TransferObjectEntityToTransferObjectMapper,
    val transferObjectEntityListToTransferObjectsListMapper: TransferObjectEntityListToTransferObjectsListMapper
)
